### ISSUE TITLE
BUG: commenting on an annotation

### ISSUE THREAD

**Issue by univiest** [rwthmoodle/moodle-mod_pdfannotator#101]
Hello,
we found a bug concerning posting comments. 
**Steps to reproduce:**
- highlighting a text passage and create an annotation for it 
- clicking on an annotation and answering to it
- when pressing the button "answer" an error message appears (attached file)
![pdfannotation_commenting](https://github.com/rwthmoodle/moodle-mod_pdfannotator/assets/143176574/614eb25a-c371-4210-aadb-419868f5367a)

**Comment by univiest** [comment]
Hello,
the bug occured with editor TinyMCE and editor Atto. We are currently on version  v1.5 release 4 (2023052300).

**Comment by t-schroeder** [comment]
This is fixed with Release 1.5.5
