### ISSUE TITLE
Change the monologo for 4.4

### ISSUE THREAD

**Issue by mwreichel** [rwthmoodle/moodle-mod_pdfannotator#114]
Hi,

paralell to the pull request #105 of @lucaboesch, we created for our moodle installation a monologo for 4.4 for mod_pdfannotator in the new style. I'm not used doing a pull request in github, but I'd like to share this with you too.

FYI: Up to 4.3 it was necessary to have the monologo as SVG and PNG, with 4.4 the new monologo is only used as SVG, therefore a general change with this version would be necessary.

![monologo](https://github.com/user-attachments/assets/5056c8e1-e828-464f-8a6a-277353fcebe5)

All the best,
Martin

**Comment by Amrita1991** [comment]
this is fixed in v1.5.7
We have used the PR from @lucaboesch officially .
