### ISSUE TITLE
Some locallib.php functions without the prefix

### ISSUE THREAD

**Issue by mudrd8mz** [rwthmoodle/moodle-mod_pdfannotator#12]
https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

Functions like `compare_votes_descending()` need either be renamed to something like `pdfannotator_compare_votes_descending()` or even better `mod_pdfannotator_compare_votes_descending()`. Alternatively, be converted to static methods of some class with correct name or namespace.

**Comment by eggSmellFart** [comment]
This issue will be relsoved with the next release of the plugin.
