### ISSUE TITLE
PDF not displayed in latest plugin version (2024112600) on Postgres

### ISSUE THREAD

**Issue by samwitzig** [rwthmoodle/moodle-mod_pdfannotator#123]
When using the latest plugin-version (2024112600) on Moodle 4.5.1 with Postgres, pdfs are successfully uploaded and stored in /moodledata, pdf annotator does however not display the pdf. Debugging turned on in Moodle does not provide further information. 

The browser reports:
Source map error: Error: request failed with status 404

Uncaught TypeError: $ is not a function
    addDropdownNavigation <<URL to Moodle>>/mod/pdfannotator/shared/locallib.js?ver=00002:76
    startOverview <<URL to Moodle>>/mod/pdfannotator/shared/overview.js?ver=00002:26
    execCb <<URL to Moodle>>/lib/javascript.php/1733838854/lib/requirejs/require.min.js:5
    check <<URL to Moodle>>/lib/javascript.php/1733838854/lib/requirejs/require.min.js:5
    enable <<URL to Moodle>>/lib/javascript.php/1733838854/lib/requirejs/require.min.js:5
    init <<URL to Moodle>>/lib/javascript.php/1733838854/lib/requirejs/require.min.js:5
    o <<URL to Moodle>>/lib/javascript.php/1733838854/lib/requirejs/require.min.js:5
    setTimeout handler*req.nextTick< <<URL to Moodle>>/lib/javascript.php/1733838854/lib/requirejs/require.min.js:5
    o <<URL to Moodle>>/lib/javascript.php/1733838854/lib/requirejs/require.min.js:5
    requirejs <<URL to Moodle>>/lib/javascript.php/1733838854/lib/requirejs/require.min.js:5
    startOverview <<URL to Moodle>>/mod/pdfannotator/shared/overview.js?ver=00002:18
    <anonymous> <<URL to Moodle>>/mod/pdfannotator/view.php?id=1139484&action=overview:1067
    _notify <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:19
    notify <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:19
    _notify <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:18
    _procSubs <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:18
    fireSimple <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:18
    _fire <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:18
    fire <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:19
    _load <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:31
    o <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:31
    g <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:1
    <anonymous> <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:32
    <anonymous> <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:32
    _attach <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:2
    _attach <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:1
    _use <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:2
    use <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:2
    <anonymous> <<URL to Moodle>>/theme/yui_combo.php?rollup/3.18.1/yui-moodlesimple-min.js:97

**Comment by Amrita1991** [comment]
The solution for this is now available with version 2024121200. The branch 'main' and 'MOODLE_404+' has the changes.
However, we have tested this on MySQL only. Please test if the solution works for Postgres too and report back.

**Comment by samwitzig** [comment]
Thank you for the fix - works on Postgres (tested with MOODLE_404+-branch). There is now another issue --> select "Overview" in the annotated PDF -> Questions (unsolved) - shall I report in this issue or do you prefer a new one?
