### ISSUE TITLE
Missing method in output\mobile (while accessing H5P content in Moodle App)

### ISSUE THREAD

**Issue by ewout** [rwthmoodle/moodle-mod_pdfannotator#18]
While accessing a H5P activity in the Moodle App, I get a coding error ("must be fixed by developer"): Missing method in \mod_pdfannotator\output\mobile (see attached screen capture)

This is even the case when I disabled the pdf annotator plugin in Moodle. 

Needless to say, this seems bad...

<img src="https://user-images.githubusercontent.com/6329/62836846-f4f16b00-bc3d-11e9-8e4c-c2bcd34f4f1c.jpg" width="400" />

**Comment by andreasschenkel** [comment]
Just run into the same problem ... Is there a workarround?

**Comment by andreasschenkel** [comment]
I have not very much experience in plugin development!!!!!!!!!
I created a file in. ***/mod/pdfannotator/classes/output/mobile.php with the following content and now the h5p-Content is shown in the App:


?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace mod_pdfannotator\output;

defined('MOODLE_INTERNAL') || die();

use context_module;
use mod_pdfannotator;

class mobile {

    public static function mobile_course_view($args) {
        return array(
            'templates'  => array(
                array(
                    'id'   => 'main',
                    'html' => $OUTPUT->render_from_template('mod_pdfannotator/mobile_view_page', $data),
                ),
            ),
        );
    }
}
