### ISSUE TITLE
Missing Buttons 'Save and return to course / and display' & 'Cancel'

### ISSUE THREAD

**Issue by kirsten-k** [rwthmoodle/moodle-mod_pdfannotator#19]
The buttons for "Save and return to course", "Save and display" and "Cancel" are missing while editing the plugin settings.
The error occurs only in the Clean-Theme or in bootstrapbase themes.
The CSS of the plugin shows that the buttons are marked with class="hidden" and also visibility="hidden". If I remove this temporarily, the buttons are displayed correctly.

**Comment by eggSmellFart** [comment]
> The buttons for "Save and return to course", "Save and display" and "Cancel" are missing while editing the plugin settings.
> The error occurs only in the Clean-Theme or in bootstrapbase themes.
> The CSS of the plugin shows that the buttons are marked with class="hidden" and also visibility="hidden". If I remove this temporarily, the buttons are displayed correctly.

Hi Kirsten, 
in trying to reproduce the behaviour you described i did not succeed. So would it be possible to give me some more infos? 
1. Could you give me the last 3 parts of the URL ?
2. Could you give the specific piece of code where you saw the hidden class/attribute and your Moodle Version ? 
3. Could you provide a screeshot ?
4. Do you make use of the css input field of the theme ?

**Comment by kirsten-k** [comment]
Hi,
our Moodle-Version is 3.5.
1. when in editing-modus it's "&return=1"
2. I think you will see it in the Screenshot.
3. 
![pdfannotate1](https://user-images.githubusercontent.com/54101359/64022696-0f30b180-cb37-11e9-8d3d-1120e4bbbed1.PNG)

![pdfannotate2](https://user-images.githubusercontent.com/54101359/64022715-1788ec80-cb37-11e9-9b93-ccefb2e54d2d.PNG)
4. Don't understand the question ;)

Thanks for your help!

**Comment by eggSmellFart** [comment]
Hi Kirsten,
thank you for your fast response. Sorry but we werent able to reproduce the described behaviour in a fresh moodle 3.5 install with either the clean theme or the bootstrap theme. If you could provide something like a test user for me I could try to figure out whats wrong by checking the code your server generates on o a given request. 
But because we werent able to reproduce the missing buttons with a fresh install we think that the problem is an interaction with another Plugin or some custom CSS in your Moodle.
If you like to send me the test-user data here is my email: offermann@itc.rwth-aachen.de

**Comment by danowar2k** [comment]
The moodle Clean and bootstrapbase theme shouldn't make a difference. There are lines in styles.css of your plugin:
https://github.com/rwthmoodle/moodle-mod_pdfannotator/blob/5da7f5a5271bff100d4814050036b57f976b1aa3/styles.css#L1-L4

Any moodleform has a <fieldset class="hidden"> at the end which is the fieldset that contains the buttons.

This CSS rule (present in your master) hides the buttons.

We're sorry, but we would need to provide you with VPN access to get to the 3.5 test instance. I'll see what I can do...

**Comment by danowar2k** [comment]
Your CSS rule seems to be more specific than the Moodle bootstrapbase theme rule that prevents the hiding of the buttons. This file here https://github.com/moodle/moodle/blob/MOODLE_35_STABLE/theme/bootstrapbase/less/moodle/undo.less
corrects some name clashes between Moodle classes and Bootstrap 2.3.2 classes.

In particular, here
https://github.com/moodle/moodle/blob/e8b6cb418f800919faddaac2b1172f21bbfeadf4/theme/bootstrapbase/less/moodle/undo.less#L88-L106
is the bootstrapbase rule that prevents the fieldset with buttons to be hidden.

**Comment by danowar2k** [comment]
Also,
4. We don't use the CSS setting of the clean theme.

**Comment by eggSmellFart** [comment]
Hi, thanks for the quick reposnse. i see the problem now. I was a bit confiused, because there is a bootstrap theme  and a bootstrapBASE theme. I was trying to get the problem reproduced with the wrong (bootstrapBASE) theme. 
the same line of code looks like this for the bootstrapBASE theme. 

```css
fieldset.hidden
{
    display: inherit !important;
    visibility: inherit !important;
}
```
https://github.com/bmbrands/theme_bootstrap/blob/794d5c6959c5daee84b362a1afc73d34112ddeb8/style/moodle.css#L9061-L9079

So I was not able to see the missing buttons because of the difference between the bootstrap theme you use and the bootstrapbase Theme that was installed on my test moodle. 
So we are wokring on a fix for the next release. Thanks for your help. cheers

**Comment by eggSmellFart** [comment]
Hi There, 
This issue is fixed and closed with the  new version.
cheers

**Comment by danowar2k** [comment]
Excuse me, but the release 1.3 still contains the above lines in the styles.css file.

If you didn't remove those lines, what did you do to fix the vanished buttons?

(We installed release 1.3; the buttons are still gone)

**Comment by danowar2k** [comment]
> Hi, thanks for the quick reposnse. i see the problem now. I was a bit confiused, because there is a bootstrap theme and a bootstrapBASE theme. I was trying to get the problem reproduced with the wrong (bootstrapBASE) theme.
> the same line of code looks like this for the bootstrapBASE theme.
> 
> ```css
> fieldset.hidden
> {
>     display: inherit !important;
>     visibility: inherit !important;
> }
> ```
> 
> https://github.com/bmbrands/theme_bootstrap/blob/794d5c6959c5daee84b362a1afc73d34112ddeb8/style/moodle.css#L9061-L9079
> 
> So I was not able to see the missing buttons because of the difference between the bootstrap theme you use and the bootstrapbase Theme that was installed on my test moodle.
> So we are wokring on a fix for the next release. Thanks for your help. cheers

This comment still confuses me.
A normal Moodle 3.5.x install comes with the following themes:

* boost (no parent themes)
* bootstrapbase (no parent themes)
* clean (parent: bootstrapbase)
* more (parents: clean, bootstrapbase)

(see https://github.com/moodle/moodle/tree/v3.5.8/theme)

The normal/core Moodle theme named "bootstrapbase" doesn't have the lines you mention above, see https://github.com/moodle/moodle/blob/4a852e846705b7a396895cba7b2da348af170a50/theme/bootstrapbase/style/moodle.css#L15849-L15866

Up above you wrote
> Hi, thanks for the quick reposnse. i see the problem now. I was a bit confiused, because there is a bootstrap theme and a bootstrapBASE theme. I was trying to get the problem reproduced with the wrong (**bootstrapBASE**) theme.
> the same line of code looks like this for the **bootstrapBASE** theme.

While you probably (?) meant
> Hi, thanks for the quick reposnse. i see the problem now. I was a bit confiused, because there is a bootstrap theme and a bootstrapBASE theme. I was trying to get the problem reproduced with the wrong (**bootstrap**) theme.
> the same line of code looks like this for the **bootstrap** theme.

Am I assuming correctly?

**Comment by eggSmellFart** [comment]
Hi there, 
we updated the plugin via [https://moodle.org/plugins/mod_pdfannotator]( https://moodle.org/plugins/mod_pdfannotator). Please let us know if the issue is reloved now. 
cheers

**Comment by danowar2k** [comment]
This issue is internally reported to be resolved.
