### ISSUE TITLE
Privacy,Copyright&Security Concerns

### ISSUE THREAD

**Issue by univietw** [rwthmoodle/moodle-mod_pdfannotator#22]
This plugin seems use the highchart.js-library which you didn't mention in your readme. With the license for this js-library you are not supposed to use it for free, except if you are a government/non-profit organization, but you still need to contact them for using it from what I understood in the plugin.
Anyways: whoever will use your statistics page will show to their company that the user has used the plugin on your page, which leads me to my privacy concern
Combined with the issue #9 which is a serious security issue and #12 which can lead to side effects we will not use this plugin and I can only give the advice to think twice about using this plugin.

**Comment by goggo24** [comment]
If we would provide a pull request for this, would you you accept it? Greetings from Vienna.

**Comment by eggSmellFart** [comment]
Hi there, issues #9 and #12 will be taken care of in the next update.

**Comment by goggo24** [comment]
good news - thanks.
