### ISSUE TITLE
Hebrew fonts render incorrectly

### ISSUE THREAD

**Issue by nadavkav** [rwthmoodle/moodle-mod_pdfannotator#26]
It seems this PDF.js version does not render Hebrew letter glyphs correctly.
![image](https://user-images.githubusercontent.com/231168/67150918-8f1d0180-f2c6-11e9-9b04-a7a3c9dd04f4.png)

And it looked fixed on the latest stable version of PDF.js
Or maybe I am not using the proper Hebrew TTF fonts?

Can you please see if you can upgrade the PDF.js library? or instruct me how do do it myself?

**Comment by nadavkav** [comment]
Seemed like a minor issue after all...
`.path-mod-pdfannotator .pdfViewer .page {
    direction: ltr !important;
}`

**Comment by nadavkav** [comment]
Actually, it would be event better if you added the following to the styles.css
```
.path-mod-pdfannotator .pdfViewer .page {
    /*rtl:ignore*/
    direction: ltr !important;
}
```

**Comment by eggSmellFart** [comment]
Hi there, 
as far as i can see, there isn't an issue anymore on your side, and i don't get what the real  difference in your snippet of CSS is. (except the !important attribute and a commented Line of code).
So for now im closing this issue 
cheers

**Comment by nadavkav** [comment]
Hi @eggSmellFart , indeed there is no issue anymore, but I suggested you add the above CSS code at the end of your styles.css file, to support other RTL users.

The difference between the two parts is /*rtl:ignore*/ which keep the direction: ltr; in RTL mode and does not auto flip it to direction:rtl; as the Moodle scss compiler does.
