### ISSUE TITLE
Provide an option to use internal Moodle latex-API

### ISSUE THREAD

**Issue by univietw** [rwthmoodle/moodle-mod_pdfannotator#27]
Some Privacy concerns may be removed by using the latex on the server if available. This should be made available through the admin settings. Since Privacy is a big concern at our university we need this option.
See #28

**Comment by goggo24** [comment]
Have you already decided if you will accept our pull request or not? The pull requests includes a new adminsetting, where anyone can decide if the instance uses the internal Moodle API (default) or Google Charts API. We would be very happy if you would accept it for the next version, please let us know. Thanks.

**Comment by eggSmellFart** [comment]
I have just merged your pull request. So the next version released will have added your functionality.
cheers

**Comment by goggo24** [comment]
Great to hear - thanks!

**Comment by banditjt** [comment]
Hi,
can you tell me when you will release the next version?

**Comment by goggo24** [comment]
When will you release the next version?
