### ISSUE TITLE
Email Notifications For All Participants

### ISSUE THREAD

**Issue by silversufer** [rwthmoodle/moodle-mod_pdfannotator#30]
Teachers can divide their course participants into groups and let them work with the PDF Annotator plugin according to their group affiliation. Teachers and students are allowed to ask questions about text passages. Students receive email notifications from the plugin, which unfortunately does not distinguish between groups. So if questions are posted, each student receives an email about the posted question. This can be very confusing for the students, because they will be informed about questions from other groups, which they cannot see themselves. You can set the email notification of group membership so that only the group members receive an email with new questions and not all course participants from the course.

**Comment by tjettmers** [comment]
In addition to this, the link in the E-Mail leads to the notification preferences of the person who commented, e.g. /message/notificationpreferences.php?userid=xxxx
Moodle blocks access, but the name and profile image will still be visible to anyone following the link

**Comment by t-schroeder** [comment]
Hi @tjettmers,

thanks a lot for that hint. We have fixed that wrong link.

We haven't gotten around to implement the annotation visibility based on groups yet, though.

**Comment by Friederike-cil** [comment]
E-Mail notifications are now disabled by default.
