### ISSUE TITLE
Delete Content After Backing Up And Restoring The Courses

### ISSUE THREAD

**Issue by silversufer** [rwthmoodle/moodle-mod_pdfannotator#31]
After backing up and restoring the courses, the comments within the Moodle activity are not deleted. This leads to different problems. Can you delete the content (comments, questions, likes, etc.) after restoring the course environment, as is the case with forums, glossaries and other Moodle activities?

**Comment by Friederike-cil** [comment]
Hi, 
we added this to our backlog, but we won't implement it in the near future

Kind regards
Friederike

**Comment by Friederike-cil** [comment]
fixed
