### ISSUE TITLE
plugin_pdfannotator

### ISSUE THREAD

**Issue by amarcocig** [rwthmoodle/moodle-mod_pdfannotator#33]
Buongiorno,

è la prima volta che mi trovo qui, e spero di seguire le regole.
Avrei una domanda da fare: ho installato il plugin [PDF Annotator v1.4 rilascio 2]. uso moodle ver. 3.2.9.
Dopo l'installazione non visualizzo nulla. Cioè pagina bianca. Inoltre non rimane aggiunta l'attività creata.
Chiedo se possibile delle soluzioni ...

Ringraziando in anticipo, saluto

**Comment by t-schroeder** [comment]
Hi,

I just tested with Moodle 3.2 and noticed that it doesn't work for a bunch of reasons. The earliest supported version is Moodle 3.3 with some of the earlier releases of this plugin. Apparently the supported Moodle versions aren't set currectly for all of the releases.

Sorry if that doesn't fix the problem for you. But Moodle 3.2 is already a couple years old and we no longer support it.

**Comment by t-schroeder** [comment]
FYI: I just tested the latest release of this plugin on Moodle 3.5 which is a LTS version and that works.
