### ISSUE TITLE
Strings hardcoded

### ISSUE THREAD

**Issue by dinism** [rwthmoodle/moodle-mod_pdfannotator#34]
Thanks for the plugin
I'm a PT-PT translator. Some strings are hardcoded.
![imagem](https://user-images.githubusercontent.com/14828021/89432078-95d31300-d738-11ea-8916-eed061082baa.png)

**Comment by t-schroeder** [comment]
Hello,

this is the name of the PDFannotator instance. It's not hardcoded, it's provided by the user.

**Comment by dinism** [comment]
Sorry about this.
Thanks for the plugin. :)

**Comment by t-schroeder** [comment]
No worries :) Closing this issue
