### ISSUE TITLE
Settings for sending emails

### ISSUE THREAD

**Issue by profwellingtonferreira** [rwthmoodle/moodle-mod_pdfannotator#35]
Question asked by Matthias Ginger on the moodle website

"Notifications are on by default. Could that be changed?
Otherwise teachers will get a lot of messages (forwarded to e-mail).
I know, it is possible to switch notifications off but once a user is aware of it, there could already be a lot of notifications to clean up. This is especially problematic with courses shared by several teachers.
The best solution would be an option in the activity itself (like in forums). "

Could you please analyze this improvement? I believe that many users have this same need.

**Comment by profwellingtonferreira** [comment]
My institution uses moodle version 3.7

**Comment by t-schroeder** [comment]
Thanks for the suggestion. Maybe we will do something like the forum subscription model in the future. For now I just changed the default setting for the new question notification to be popup only, no emails. The other kinds of notifications (forwarded and reported questions) will still by default generate email notifications. Does that work for you or did you have some different default settings in mind?
