### ISSUE TITLE
String in deutch

### ISSUE THREAD

**Issue by dinism** [rwthmoodle/moodle-mod_pdfannotator#36]
In AMOS, the string: forwardedquestiontext:
![imagem](https://user-images.githubusercontent.com/14828021/89518230-87d1d080-d7d2-11ea-8831-786f4904d27c.png)

**Comment by t-schroeder** [comment]
Thanks for noticing. I fixed it on GitHub. We will create a new plugin release tomorrow probably. Then it will be fixed in AMOS, too.
