### ISSUE TITLE
DML Exception on Postgres DB

### ISSUE THREAD

**Issue by nino2205** [rwthmoodle/moodle-mod_pdfannotator#37]
In locallib.php line 511-513 the SQL-Syntax won't work on Postgres DB.
Named selects has to be in quotation marks.
```
$sql = "SELECT max(a.timecreated) as 'last_annotation', max(c.timemodified) as 'last_comment' "
            . "FROM {pdfannotator_annotations} a LEFT OUTER JOIN {pdfannotator_comments} c ON a.id = c.annotationid "
            . "WHERE a.pdfannotatorid = ?";
```

**Comment by HDonath** [comment]
Hi,
we added this to our backlog, but we won't implement it in the near future.

**Comment by dahrens** [comment]
I inherited the moodle installation from @nino2205 and currently consolidate small patches.
At us this is solved like this right now:

```php
$sql = "SELECT max(a.timecreated) as ".'"last_annotation"'." , max(c.timemodified) as ".'"last_comment"'." "
            . "FROM {pdfannotator_annotations} a LEFT OUTER JOIN {pdfannotator_comments} c ON a.id = c.annotationid "
            . "WHERE a.pdfannotatorid = ?";
```

Any chance to get this merged by a pull request, or do you plan to approach postgresql support in general? (I'm not that deep in moodle development right now, just in case the question is completely insane :) )

**Comment by Friederike-cil** [comment]
Hi,
a new version is published on the branch "dev". I hope this is fixed now :)
