### ISSUE TITLE
Error Showing the PDF File

### ISSUE THREAD

**Issue by randiproska** [rwthmoodle/moodle-mod_pdfannotator#42]
I have an issues opening the pdf file on the browser. It shows "an error occurred while opening the PDF file". Is there any solutions?

Thanks

**Comment by Friederike-cil** [comment]
Hi,
which browser do you use?
One of our users had the same problem with Chrome, but with Firefox he could open the pdf.
We assume there is a problem with the pdf.js library but we haven't been able to find out what it is yet.

**Comment by t-schroeder** [comment]
Can you provide some more information? Is there some error in the JavaScript console? Does this only happen with certain PDFs? Have you tried with browser extensions disabled? Have you tried turning hardware acceleration off? Have you tried clearing your browser cache?

**Comment by randiproska** [comment]
> Hi,
> which browser do you use?
> One of our users had the same problem with Chrome, but with Firefox he could open the pdf.
> We assume there is a problem with the pdf.js library but we haven't been able to find out what it is yet.

Hi @Friederike-cil, I already try with Chrome, Firefox, Edge, and Safari. It is still not working, but it works on mobile web browser. What should I do?

**Comment by randiproska** [comment]
> Can you provide some more information? Is there some error in the JavaScript console? Does this only happen with certain PDFs? Have you tried with browser extensions disabled? Have you tried turning hardware acceleration off? Have you tried clearing your browser cache?

Hi @t-schroeder, It shows "An error occurred while opening the PDF file". I already try using various pdf file, clear browser cache and no further error showed. However it still cannot show the pdf and it automatically download the pdf file

**Comment by t-schroeder** [comment]
Hi @randiproska can you open the developer tools of your browser, than reload the page and see if there is some additional error message logged in the "Console" tab?

**Comment by randiproska** [comment]
Hi @t-schroeder, it showed this error:

`pdf.worker.js:42346 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
supportsMozChunkedClosure @ pdf.worker.js:42346
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
content.js:657 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
safecheck.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
DevTools failed to load SourceMap: Could not load content for http://proska.tech/mod/pdfannotator/shared/pdf-annotate.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
[Violation] Forced reflow while executing JavaScript took 40ms
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
content.js:657 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
safecheck.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
content.js:657 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
safecheck.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
content.js:657 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
safecheck.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
content.js:657 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
safecheck.js:132 `

**Comment by randiproska** [comment]
The issue is solved. The site should be secured or "https"
