### ISSUE TITLE
highlight and strikeout tools not working

### ISSUE THREAD

**Issue by tessa-fabry** [rwthmoodle/moodle-mod_pdfannotator#46]
The highlight and strikeout tools are not working. I am able to select the tool and the cursor changes correctly but will not highlight or strikeout text. I am looking into this myself but no luck so far

Moodle Version - 2020061506.00 (3.9.6)
Plugin Version - 2021012600

Just discovered that this works on the version downloaded from here https://moodle.org/plugins/pluginversions.php?plugin=mod_pdfannotator which is version 2020080400 (1.4.2)

**Comment by andreasschenkel** [comment]
We clone the code from git and the version 
$plugin->version   = 2021012600; // The current module version (Date: YYYYMMDDXX
).
$plugin->release  = 'PDF Annotator v1.4 release 5';
has this issue. Does the zip-Version on moodle.org work correctly?

**Comment by HDonath** [comment]
Hi,

we will soon release a new version which will fix this issue.
