### ISSUE TITLE
Class comment should be defined in a namespace

### ISSUE THREAD

**Issue by xuangui2018** [rwthmoodle/moodle-mod_pdfannotator#49]
class comment is not defined in a namespace.

Moodle also has a class with the same name in comment/lib.php

Please see the following error:
Fatal error: Cannot declare class comment, because the name is already in use in /var/www/site/mod/pdfannotator/classes/output/comment.php on line 27
PHP Fatal error:  Cannot declare class comment, because the name is already in use in /var/www/site/mod/pdfannotator/classes/output/comment.php on line 27

**Comment by Friederike-cil** [comment]
Hi,
thanks for reporting this issue. We will fix this

**Comment by t-schroeder** [comment]
Fixed in new release 1.4.7
