### ISSUE TITLE
 v1.4 release 7: Backups are no longer enabled

### ISSUE THREAD

**Issue by Pedagotheque** [rwthmoodle/moodle-mod_pdfannotator#52]
Hi,

I updated the PDF Annotator plugin to the v1.4 release 7 (2021060100) and backups are no longer enabled. I get the following alert: 
**undefined - Error**
Error reading from database

Are you considering fixing this?

Thank you very much,
Regards
__
Camille

**Comment by Friederike-cil** [comment]
Hi,
I can't reproduce this error.
Could you please provide some further information (Which Moodle Version and Database are you using? Did you try to backup one activity or the whole course? ...)

If you are using PostgreSQL please try the PDFAnnotator version on the branch "dev"

Kind regards
Friederike

**Comment by Pedagotheque** [comment]
Hi,

We are using Moodle  3.9.3+ . I get the error whenever I try to backup a single activity or the entire course. 

Indeed, we are using PostgreSQL and I will try the "dev" branch version of the plugin and keep you up.

Thank you,
Regards
__
Camille

**Comment by Pedagotheque** [comment]
When using PostgreSQL, the "dev" branch version of the plugin fixes the problem.

Thank you very much!
Regards
__
Camille
