### ISSUE TITLE
Error in line 82 of /mod/pdfannotator/view.php

### ISSUE THREAD

**Issue by jonlan** [rwthmoodle/moodle-mod_pdfannotator#55]
After updating to the newest version we receive the following error.

1. Create a new pdf Annotator activty.
2. Save and open it.
3. The following error appears:

Exception - Class 'core_completion\cm_completion_details' not found

More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 82 of /mod/pdfannotator/view.php: Error thrown

Versions:
- PDF Annotationmod_pdfannotator | PDF Annotator v1.4 release 82021082600
- Moodle 3.10.6+ (Build: 20210827)

**Comment by jonlan** [comment]
This code seems to be the cause:
https://github.com/rwthmoodle/moodle-mod_pdfannotator/commit/2d3040cb5a0868b8c50abff9e7050a2007384cbe

**Comment by Friederike-cil** [comment]
Hi,
for the newest version Moodle 3.11 is required. I updated the $plugin->requires attribute now.

You can use the v1.4.7.2 release for Moodle 3.10 which should also work with older Moodle versions.
Or you remove the following lines from the code (at the end of view.php)
```// Render the activity information.
$modinfo = get_fast_modinfo($course);
$cminfo = $modinfo->get_cm($cm->id);
$completiondetails = \core_completion\cm_completion_details::get_instance($cminfo, $USER->id);
$activitydates = \core\activity_dates::get_dates_for_module($cminfo, $USER->id);
echo $OUTPUT->activity_information($cminfo, $completiondetails, $activitydates);```
