### ISSUE TITLE
Make links in comments clickable

### ISSUE THREAD

**Issue by proedie** [rwthmoodle/moodle-mod_pdfannotator#67]
At the moment, links in comments are not recognised. They should be parsed as links and be clickable.

**Comment by Friederike-cil** [comment]
Hi,
we replaced the current editor for the atto editor to achieve this. It will be published with the next version we are currently preparing. We are currently updating the plugin to make it work with Moodle 4.0. We are also integrating some of the feature requests from the past months. The release should be ready sometime this summer.

**Comment by t-schroeder** [comment]
Since Release v1.5.1 this works for newly created comments since they are no longer necessarily written as plaintext. The plugin now uses the user's configured text editor which is Atto by default which uses the HTML format by default which supports links.
