### ISSUE TITLE
Differences between version tags with and without "_Moodle3.10"

### ISSUE THREAD

**Issue by slaudel** [rwthmoodle/moodle-mod_pdfannotator#73]
Hello,

this is not a real issue, it's more of an understanding question.
What are the differences between the version tags with and without "_Moodle3.10"? 
Which one would/should we use with Moodle 3.9?
It is kind of irritating, because version.php is for both options identical. 

Maybe this could be annotated in the [readme](https://github.com/rwthmoodle/moodle-mod_pdfannotator/blob/v1.4.11/README.md)?

Thanks for clarification.

**Comment by Friederike-cil** [comment]
Hi,
the versions without "_Moodle3.10" require Moodle 3.11. In some older releases I forgot to update $plugin->requires in the version.php but it is correct for the latest release.
In order to support older Moodle Versions we released versions with "_Moodle3.10". You can use it for Moodle 3.9
