### ISSUE TITLE
language strings issues

### ISSUE THREAD

**Issue by univietw** [rwthmoodle/moodle-mod_pdfannotator#78]
With the version 1.5.1 came some changes in the language strings in the plugin. This problem persists in version 1.5.2
Since this update we cant change our lang strings in moodle anymore:
(https://user-images.githubusercontent.com/17589223/204532498-25de48ad-006d-483b-927c-8e2c05b16e59.png)
This comes from a duplicate name in the lang strings:
!(https://user-images.githubusercontent.com/17589223/204532735-5bf034c1-3e43-4019-91c2-9dbb0b182633.png)

I looked up the moodle tracker issues and there also seems to be a problem with uppercase langstring IDs. (see https://tracker.moodle.org/browse/MDL-67302)
Because of this I would recommend to first rename the lang string in question and release a new minor version so AMOS only has one of these language strings
Secondly I would consider switching to only lower-case language identifiers as its easier to avoid errors.

**Comment by nisaDoc** [comment]
Hello,
thank you for reporting. We are working on that.

**Comment by nisaDoc** [comment]
Hello,
new release is there with fixes for this problem and another changes (see: [v1.5.3](https://github.com/rwthmoodle/moodle-mod_pdfannotator/releases/tag/v1.5.3)).
and we are currently not planning to switch the lang strings to only lower-case. But, we are open for merge request of that improvement suggestion.

Best regards,
Nisa
