### ISSUE TITLE
Double label "error:printcomments" in language-file pdfannotator.php: 

### ISSUE THREAD

**Issue by franzvinzenz** [rwthmoodle/moodle-mod_pdfannotator#79]
In the file mod/pdfannotator/lang/en/pdfannotator.php is a double Label in Line 115 and 124.

$string['error:printComments'] = 'Error with data from server.';
$string['error:printcomments'] = 'An error has occured while trying to open the comments in a pdf.';

The table for language-customization uses an index, which is NOT case-sensitive.
It throws an duplicate-key-error.

**Comment by nisaDoc** [comment]
Hello,
thank you for reporting. We have fixed this problem in the latest version v1.5.3.

Best regards,
Nisa
