### ISSUE TITLE
Unsolved questions

### ISSUE THREAD

**Issue by mudrd8mz** [rwthmoodle/moodle-mod_pdfannotator#8]
The page view.php?action=overviewquestions has constant title "Unsolved questions" regardless the selected filter (unsolved, solved, all).

![image](https://user-images.githubusercontent.com/85831/61156588-0be45680-a4f4-11e9-8aa9-b5678f2bd98d.png)

**Comment by eggSmellFart** [comment]
Hi there,
thank you for your help. the next relase will fix this issue.
cheers
