### ISSUE TITLE
Please release bugfix PHP 8.0 issue for 3.11 at moodle.org

### ISSUE THREAD

**Issue by andremenrath** [rwthmoodle/moodle-mod_pdfannotator#82]
https://github.com/rwthmoodle/moodle-mod_pdfannotator/commit/2170b65eac64f7c00a4d47ee15ba65d64580db7e

This bugfix is not released at moodle.org for the 3.11 branch though Moodle 3.11 supports PHP 8.0 which is the reason this bug appeared.

**Comment by nisaDoc** [comment]
Hello,
thank you for reporting this issue. Our newest release is still compatible to the 3.11. You can use it also for 3.11

**Comment by andremenrath** [comment]
@nisaDoc  Thanks for the reply and clarification. However, this does make our automated deployment more complicated. However, we'll be moving to Moodle 4.x soon, so it won't be a burden for long.

**Comment by nisaDoc** [comment]
Ok, nice to hear.
So, I will close this issue.
Thx for using our plugin

**Comment by andremenrath** [comment]
Thanks a lot for sharing this plugin with the community!
