### ISSUE TITLE
Issue opening a PDF

### ISSUE THREAD

**Issue by Syonis** [rwthmoodle/moodle-mod_pdfannotator#83]
Hello, I've installed the pdfannotator and the LaTeX packages.
Now, if I create a PDF it only sayes: "Beim Öffnen der PDF-Datei ist ein Fehler aufgetreten" (An error occurred while opening the PDF file).
The Apache2 says:
` [php7:notice] [pid 9667] [client x.x.x.x:27346] Default exception handler: Fehler beim Lesen der Datenbank Debug: ERROR:  invalid input syntax for type bigint: "Web-Sek_II_EF.pdf"\nSELECT 'x' FROM mdl_pdfannotator_comments WHERE id = $1 LIMIT 1\n[array (\n  0 => 'Web-Sek_II_EF.pdf',\n)]\nError code: dmlreadexception\n* line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown\n* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()\n* line 341 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()\n* line 902 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()\n* line 2010 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_recordset_sql()\n* line 1995 of /lib/dml/moodle_database.php: call to moodle_database->record_exists_sql()\n* line 1979 of /lib/dml/moodle_database.php: call to moodle_database->record_exists_select()\n* line 381 of /mod/pdfannotator/lib.php: call to moodle_database->record_exists()\n* line 5212 of /lib/filelib.php: call to pdfannotator_pluginfile()\n* line 44 of /pluginfile.php: call to file_pluginfile()\n, referer: https://url.de/mod/pdfannotator/view.php?id=52562&forceview=1
`
What can I do to fix that?
Thx a lot in advanced

**Comment by Syonis** [comment]
Oh shit. I noticed that the Plugin is only for Version < 4.0. Sorry for that.
Is it planned to rise these Plugin to 4.1?

**Comment by nisaDoc** [comment]
Hello,

thank for using our plugin and for reporting this issue. Our newest release is actually compatible to the 3.11. I think, this problem is the DB Problem mentioned in #80.
I you are in hurry, you can locally pull the pull request in #80.
I dont think, we would be able make a release immediately.
For the 4.1 is still not planned, but we will add it to our backlog.

**Comment by Syonis** [comment]
Thx a lot. I`ll waiting for a compatible Version with 4.1.
Until that I'm afraid of killing my school. ;)

**Comment by nisaDoc** [comment]
Hello,
new release is there with fix for this problem.

cheers
Nisa
