### ISSUE TITLE
Privacy provider does not implement userlist

### ISSUE THREAD

**Issue by matthewhilton** [rwthmoodle/moodle-mod_pdfannotator#84]
According to the Moodle docs:

https://moodledev.io/docs/apis/subsystems/privacy

> In addition to these requirements, since Moodle 3.4.6, 3.5.3, any plugin which implements the plugin provider interface must also implement the \core_privacy\local\request\core_userlist_provider provider and implement functions:
> 
>     get_users_in_context - to locate the users who hold any personal data in a specific context; and
>     delete_data_for_users - to delete data for multiple users in the specified context.

This test is failing:

```
1) core_privacy\privacy\provider_test::test_userdata_provider_implements_userlist with data set "mod_pdfannotator" ('mod_pdfannotator', 'mod_pdfannotator\privacy\provider')
Failed asserting that false is true.

/var/www/ec-41/privacy/tests/privacy/provider_test.php:213
/var/www/ec-41/lib/phpunit/classes/advanced_testcase.php:80
```

**Comment by nisaDoc** [comment]
Hi,

thx for using our issue and for the pull request you did for this problem.
we will check it.

Cheers,
Nisa

**Comment by nisaDoc** [comment]
Hello,
new release is there with fix for this problem.
I added some changes into your PR. Thx for the PR

cheers
Nisa
