### ISSUE TITLE
[Moodle 4.1][v1.5.3] Activity completion shown twice

### ISSUE THREAD

**Issue by danowar2k** [rwthmoodle/moodle-mod_pdfannotator#87]
In Boost, the activity completion button is shown twice.

![Annotation doppelter Aktivitätsabschluss](https://user-images.githubusercontent.com/10991509/234899507-1a6e13c2-5092-4a7a-9081-79121e6db461.PNG)

**Comment by danowar2k** [comment]
"Die doppelte Anzeige ist auf der Seite der Aktivität über dem Annotationstool zu finden"

The redundant buttons can be found on the activity page above the annotation tool.

**Comment by nisaDoc** [comment]
Hello,

we are currently working on a new release and this should be fixed there.
Thx for reporting and for using our plugin.

Cheers,
Nisa

**Comment by nisaDoc** [comment]
Hello,
new release is there with fix for this problem.

cheers
Nisa
