### ISSUE TITLE
Comment cannot be edited

### ISSUE THREAD

**Issue by lf1717** [rwthmoodle/moodle-mod_pdfannotator#97]
Hi there,

We use in our moodle (Version 4.1.3 build 20230424) the pdf annotation activity.

![image](https://github.com/rwthmoodle/moodle-mod_pdfannotator/assets/108652528/b87d49b5-e590-42aa-92fe-fa6de6aaa0ad)

When I will edit my comment, the edit box is not active/nothing happens.

![image](https://github.com/rwthmoodle/moodle-mod_pdfannotator/assets/108652528/bd450ddc-1485-4b0c-b423-4f2d991170ce)

Thanks for further help.

Regards,
Lydia

**Comment by nisaDoc** [comment]
Hello,
thx for reporting this issue. I cannot replicate this problem in our system. Could you send us the browser console and more infos, when the problem appears?

Cheers,
Nisa

**Comment by lf1717** [comment]
Hi,
Thanks for your reply. 
I checked it on several browsers (firefox 116.0.3, Brave, 1.57.53, Edge 115.0.1901.203) but when I click on "edit" nothing happens. 

I would like edit my comment, but it does not work. 

Regards,
Lydia

**Comment by lf1717** [comment]
Hi Nisa,

Problem solved when I change the texteditor. See #96

**Comment by goggo24** [comment]
@nisaDoc as above mentioned the problem occurs only with the new standard editor tinymce. The workaround with full screen mode of the tiny is suboptimal, with atto everythings works fine. Do you plan to support tinymce?

**Comment by Friederike-cil** [comment]
Hi,
it's fixed in the latest release 1.5.5
